# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_ratesC <- function(betavec, gamma, Ivec, S) {
    .Call('pevosim_get_ratesC', PACKAGE = 'pevosim', betavec, gamma, Ivec, S)
}

do_extinctC <- function(state, mut_var, extinct) {
    invisible(.Call('pevosim_do_extinctC', PACKAGE = 'pevosim', state, mut_var, extinct))
}

run_stepC <- function(state, t_tot, t_end, params, debug = TRUE) {
    invisible(.Call('pevosim_run_stepC', PACKAGE = 'pevosim', state, t_tot, t_end, params, debug))
}

